### ISSUE TITLE
Action unable to fetch latest tokens: Figma API key update

### ISSUE THREAD

**Issue by danielgolden** [newrelic/one-core-toolbox#45]
Hey, team ✌🏽. I noticed an unexpected issue after my NR figma account was deactivated. It seems my Figma API key is no longer valid (which makes sense given my user was removed), but that means that the GitHub action which fetches the latest color tokens no longer works because [the API key it's been provided](https://github.com/newrelic/one-core-toolbox/actions/runs/2926645797/workflow#L40) is invalid.

I think that needs to be done to fix this is provide it with a valid Figma API key.

cc: @aarongarciah, @bluefinger

**Comment by aarongarciah** [comment]
Thanks for the heads up @danielgolden!

**Comment by aarongarciah** [comment]
A new Figma API key was added and actions are back to normal. Thanks for reporting @danielgolden!
